import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistOutline = Geist({
  variable: "--font-geist-outline",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "studyHub",
  description: "Generated by studyHub",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${geistOutline} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">
        <article className="">
        <Navbar/>
        </article>
        {children}
        </body>
    </html>
  );
}
